"""
This type stub file was generated by pyright.
"""

class ContainerStartException(RuntimeError):
    ...


class ContainerConnectException(RuntimeError):
    ...


class ContainerIsNotRunning(RuntimeError):
    ...


class NoSuchPortExposed(RuntimeError):
    ...


