"""
This type stub file was generated by pyright.
"""

from typing import Optional

class Network:
    """
    Network context manager for programmatically connecting containers.
    """
    def __init__(self, docker_client_kw: Optional[dict] = ..., docker_network_kw: Optional[dict] = ...) -> None:
        ...
    
    def connect(self, container_id: str, network_aliases: Optional[list] = ...): # -> None:
        ...
    
    def remove(self) -> None:
        ...
    
    def create(self) -> Network:
        ...
    
    def __enter__(self) -> Network:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
    


