"""
This type stub file was generated by pyright.
"""

import logging
from pathlib import Path
from typing import Any, Final, Optional

LINUX = ...
MAC = ...
WIN = ...
def setup_logger(name: str) -> logging.Logger:
    ...

def os_name() -> Optional[str]:
    ...

def is_mac() -> bool:
    ...

def is_linux() -> bool:
    ...

def is_windows() -> bool:
    ...

def is_arm() -> bool:
    ...

def inside_container() -> bool:
    """
    Returns true if we are running inside a container.

    https://github.com/docker/docker/blob/a9fa38b1edf30b23cae3eade0be48b3d4b1de14b/daemon/initlayer/setup_unix.go#L25
    """
    ...

def default_gateway_ip() -> Optional[str]:
    """
    Returns gateway IP address of the host that testcontainer process is
    running on

    https://github.com/testcontainers/testcontainers-java/blob/3ad8d80e2484864e554744a4800a81f6b7982168/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L27
    """
    ...

def raise_for_deprecated_parameter(kwargs: dict[Any, Any], name: str, replacement: str) -> dict[Any, Any]:
    """
    Raise an error if a dictionary of keyword arguments contains a key and suggest the replacement.
    """
    ...

CGROUP_FILE: Final[Path] = ...
def get_running_in_container_id() -> Optional[str]:
    """
    Get the id of the currently running container
    """
    ...

