[tool.poetry]
name = "autoagent-api"
version = "0.1.0"
description = "gRPC API definitions for the AutoAgent system."
authors = ["AutoAgent Core Team <dev@autoagent.is>"]
license = "Proprietary"

packages = [{ include = "autoagent_api" }]

[tool.poetry.dependencies]
python = "^3.11"
grpcio = "^1.60.0"
protobuf = "^6.31.1"
google-api-python-client = "^2.122.0"

[tool.poetry.group.dev.dependencies]
grpcio-tools = "^1.60.0"
types-protobuf = "^6.30.0"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
